image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

environment:
  matrix:
    - PLATFORM: x86
      QTDIR: C:\Qt\5.14\msvc2017
      GENERATOR: Visual Studio 16 2019
      ARCHITECTURE: Win32
    - PLATFORM: x64
      QTDIR: C:\Qt\5.14\msvc2017_64
      GENERATOR: Visual Studio 16 2019
      ARCHITECTURE: x64

install:
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - cmake -G"%GENERATOR%" -A %ARCHITECTURE% -DCMAKE_PREFIX_PATH=%QTDIR% -DCMAKE_INSTALL_PREFIX=./install . -DFIPS_CONFIGURATION=%CONFIGURATION%

build_script:
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target PACKAGE

test_script:
  - ctest --output-on-failure

artifacts:
  - path: '*.exe'
    name: Installer

deploy:
  provider: GitHub
  auth_token:
    secure: 0dqD0nJznh5C1ljdK5XdGXiivGzx5BWbfVMAdYVRsKC1QhbBIBzFl9tvRfzcuDSp
  artifact: Installer
  on:
    appveyor_repo_tag: true
    configuration: Release
